#ifndef DEFINE_STRING
#error "DEFINE_STRING must be defined before including this file"
#endif

// clang-format off

    DEFINE_STRING(STR_CODE_GENERATOR, "Code Generator"),
    DEFINE_STRING(STR_RETURN_TO_GAME, "Return To Game"),
    DEFINE_STRING(STR_EXIT_TO_MAIN_MENU_0, "Exit To Main Menu"),
    DEFINE_STRING(STR_KNOWN_VALUE_SEARCH, "Known Value Search"),
    DEFINE_STRING(STR_UNKNOWN_VALUE_SEARCH, "Unknown Value Search"),
    DEFINE_STRING(STR_EQUAL_TO, "Equal To"),
    DEFINE_STRING(STR_EMPTY_0, ""),
    DEFINE_STRING(STR_GREATER_THAN_LAST, "Greater Than Last"),
    DEFINE_STRING(STR_LESS_THAN_LAST, "Less Than Last"),
    DEFINE_STRING(STR_DIFFERENT_TO_LAST, "Different To Last"),
    DEFINE_STRING(STR_EQUAL_TO_LAST, "Equal To Last"),
    DEFINE_STRING(STR_START, "Start"),
    DEFINE_STRING(STR_RESET_CODE_GENERATOR, "Reset Code Generator"),
    DEFINE_STRING(STR_LAST, " Last"),
    DEFINE_STRING(STR_EMPTY_1, ""),
    DEFINE_STRING(STR_EXIT_TO_MAIN_MENU_1, "Exit To Main Menu"),
    DEFINE_STRING(STR_IN_GAME_MENU, "In Game Menu"),
    DEFINE_STRING(STR_CODES_ARE_ON, "Codes Are ON"),
    DEFINE_STRING(STR_CODES_ARE_OFF, "Codes Are OFF"),
    DEFINE_STRING(STR_VIEW_SEARCH_RESULTS, "View Search Results"),
    DEFINE_STRING(STR_EMPTY_2, ""),
    DEFINE_STRING(STR_EMPTY_3, ""),
    DEFINE_STRING(STR_MEMORY_EDITOR, "Memory Editor"),
    DEFINE_STRING(STR_CHANGE_SEARCH_AREA, "Change Search Area"),
    DEFINE_STRING(STR_INCREASE_DECREASE, "C\x83:Increase  C\x82:Decrease"),
    DEFINE_STRING(STR_UP_DOWN_QUICK, "L:Up Quick  R:Down Quick"),
    DEFINE_STRING(STR_MENU_TEXT_EXIT, "'A':Menu  'Z':Numbers/Text  'B':Exit"),
    DEFINE_STRING(STR_EXIT_RETURN_TO_GAME, "'B':Exit  Start:Return to Game"),
    DEFINE_STRING(STR_OPTIONS, "Options"),
    DEFINE_STRING(STR_GOTO_ADDRESS, "Goto Address"),
    DEFINE_STRING(STR_BACK_TO_EDITOR, "Back to Editor"),
    DEFINE_STRING(STR_SELECT_DIGIT, "Left/Right:Select Digit"),
    DEFINE_STRING(STR_CHANGE_FINISH_CANCEL, "Up/Down:Change  'A':Finish  'B':Cancel"),
    DEFINE_STRING(STR_CANCEL_AND_RETURN, "Start:Cancel and Return to Game"),
    DEFINE_STRING(STR_RESOLUTION_NORMAL, "Return Resolution:Normal"),
    DEFINE_STRING(STR_RESOLUTION_HIGH, "Return Resolution:High"),
    DEFINE_STRING(STR_THERE_ARE_0_POSSIBILITIES, "There are 0 possibilities"),
    DEFINE_STRING(STR_POSSIBLE_CHEAT_CODES, "Possible Cheat Codes"),
    DEFINE_STRING(STR_SELECT_CODE, "Up/Down Select Code"),
    DEFINE_STRING(STR_ACTIVATE_ABORT, "'A':Activate 'B':Abort"),
    DEFINE_STRING(STR_RESET_CODE_GENERATOR_TO_START_AGAIN, "Reset Code Generator to Start Again"),
    DEFINE_STRING(STR_POSSIBILITIES_REMAIN, "Possibilities Remain"),
    DEFINE_STRING(STR_1_POSSIBILITY, "1 Possibility!"),
    DEFINE_STRING(STR_SEARCH_AREA, "Search Area"),
    DEFINE_STRING(STR_SEARCH_DONE, "Search done"),
    DEFINE_STRING(STR_EMPTY_4, ""),
    DEFINE_STRING(STR_EMPTY_5, ""),
    DEFINE_STRING(STR_EMPTY_6, ""),
    DEFINE_STRING(STR_RETURN_TO_THE_GAME, "Return to the game"),
    DEFINE_STRING(STR_EMPTY_7, ""),
    DEFINE_STRING(STR_BACK_TO_MAIN_MENU, "Back to Main Menu"),
    DEFINE_STRING(STR_EMPTY_8, ""),
    DEFINE_STRING(STR_EMPTY_9, ""),
    DEFINE_STRING(STR_EMPTY_10, ""),
    DEFINE_STRING(STR_EMPTY_11, ""),
    DEFINE_STRING(STR_SEARCH_ALL_OF_MEMORY_0, "Search all of memory for a known"),
    DEFINE_STRING(STR_SEARCH_ALL_OF_MEMORY_1, "value. This is useful for finding"),
    DEFINE_STRING(STR_SEARCH_ALL_OF_MEMORY_2, "scores, money etc."),
    DEFINE_STRING(STR_SEARCH_MEMORY_0, "Search memory for unknown values."),
    DEFINE_STRING(STR_SEARCH_MEMORY_1, "This search is useful for finding"),
    DEFINE_STRING(STR_SEARCH_MEMORY_2, "energy bars."),
    DEFINE_STRING(STR_RESET_THE_CODE_GENERATOR, "Reset the Code Generator."),
    DEFINE_STRING(STR_START_AGAIN, "Use this option to start again."),
    DEFINE_STRING(STR_EMPTY_12, ""),
    DEFINE_STRING(STR_VIEW_POSSIBILITIES_0, "View the list of possibilities, add"),
    DEFINE_STRING(STR_VIEW_POSSIBILITIES_1, "codes to and remove codes from the"),
    DEFINE_STRING(STR_VIEW_POSSIBILITIES_2, "active cheat list."),
    DEFINE_STRING(STR_SEARCH_FOR_A_VALUE_YOU_SPECIFY, "Search for a value you specify"),
    DEFINE_STRING(STR_EMPTY_13, ""),
    DEFINE_STRING(STR_EMPTY_14, ""),
    DEFINE_STRING(STR_START_THE_SEARCH, "Start the search"),
    DEFINE_STRING(STR_EMPTY_15, ""),
    DEFINE_STRING(STR_EMPTY_16, ""),
    DEFINE_STRING(STR_CHANGE_THE_SEARCH_AREA, "Change the search area"),
    DEFINE_STRING(STR_SELECT_FROM_AREAS, "Select from areas 1 to 9"),
    DEFINE_STRING(STR_EMPTY_17, ""),
    DEFINE_STRING(STR_SEARCH_FOR_GREATER_0, "Search for values which are now"),
    DEFINE_STRING(STR_SEARCH_FOR_GREATER_1, "greater than last time"),
    DEFINE_STRING(STR_EMPTY_18, ""),
    DEFINE_STRING(STR_SEARCH_FOR_LESS_0, "Search for values which are now"),
    DEFINE_STRING(STR_SEARCH_FOR_LESS_1, "less than last time"),
    DEFINE_STRING(STR_EMPTY_19, ""),
    DEFINE_STRING(STR_SEARCH_FOR_DIFFERENT_0, "Search for values which are now"),
    DEFINE_STRING(STR_SEARCH_FOR_DIFFERENT_1, "different to last time"),
    DEFINE_STRING(STR_EMPTY_20, ""),
    DEFINE_STRING(STR_SEARCH_FOR_THE_SAME_0, "Search for values which are still"),
    DEFINE_STRING(STR_SEARCH_FOR_THE_SAME_1, "the same as last time"),
    DEFINE_STRING(STR_EMPTY_21, ""),
    DEFINE_STRING(STR_ACTIVATE_CURRENT, "Activate the current code list"),
    DEFINE_STRING(STR_EMPTY_22, ""),
    DEFINE_STRING(STR_ENTER_THE_CODE_GENERATOR, "Enter the Code Generator."),
    DEFINE_STRING(STR_EMPTY_23, ""),
    DEFINE_STRING(STR_SET_DEFAULT_RESOLUTION_0, "Set the default screen resolution for"),
    DEFINE_STRING(STR_SET_DEFAULT_RESOLUTION_1, "returning back to the game"),
    DEFINE_STRING(STR_EMPTY_24, ""),
    DEFINE_STRING(STR_POSSIBILITIES, "Possibilities"),
    DEFINE_STRING(STR_ACTIVE_CODES, "Active Codes"),
    DEFINE_STRING(STR_EMPTY_25, ""),
    DEFINE_STRING(STR_EMPTY_26, ""),
    DEFINE_STRING(STR_HIGHLIGHT, "Highlight with up/down."),
    DEFINE_STRING(STR_COPY_TO_ACTIVE_CODES, "Copy to active codes with 'A'."),
    DEFINE_STRING(STR_MOVE_TO_ACTIVE_CODES, "To move to active codes press right."),
    DEFINE_STRING(STR_DELETE_A_CODE, "Delete a code with C\x81."),
    DEFINE_STRING(STR_EDIT_A_CODE, "Edit a code with C\x80"),
    DEFINE_STRING(STR_START_RETURNS_TO_GAME, "Start returns to game, 'B' exits"),
    DEFINE_STRING(STR_40_ACTIVE_CODES, "40 Active codes maximum!"),
    DEFINE_STRING(STR_CODE_ALREADY_ACTIVE, "This code is already active!"),
    DEFINE_STRING(STR_EDIT_VALUE, "Edit Value"),
    DEFINE_STRING(STR_FIRST_100_POSSIBILITIES, "First 100 Possibilities available"),
    DEFINE_STRING(STR_HEX_DECIMAL_MEMORY_EDITOR, "'Z':hex/decimal  C\x83:Memory Editor"),
    DEFINE_STRING(STR_TEXT_SEARCH, "Text Search"),
    DEFINE_STRING(STR_SEARCHING, "Searching Please Wait"),
    DEFINE_STRING(STR_STRING_NOT_FOUND, "String Not Found Press 'B'"),
    DEFINE_STRING(STR_8_BIT, "8 Bit Search"),
    DEFINE_STRING(STR_16_BIT, "16 Bit Search"),
    DEFINE_STRING(STR_TOGGLES_SEARCH_WIDTH, "Toggles between an 8 or 16 Bit Search"),
    DEFINE_STRING(STR_VIEW_GFX_MEMORY, "View GFX Memory"),
    DEFINE_STRING(STR_GOTO_GAMESHARK, "Goto GameShark"),
    DEFINE_STRING(STR_EQUAL_TO_8_BIT, "Equal To (0-255)"),
    DEFINE_STRING(STR_EQUAL_TO_16_BIT, "Equal To (0-65535)"),
